name: Rustlings Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    runs-on: echoja-rustlings-linux
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - uses: DavidAnson/markdownlint-cli2-action@v9
        with:
          globs: "exercises/**/*.md"
      - name: Run cargo fmt
        run: |
          cargo fmt --all -- --check
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    timeout-minutes: 20
    env:
      CARGO_HOME: ${{ runner.temp }}/cargo
      RUSTUP_HOME: ${{ runner.temp }}/rustup
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - echoja-rustlings-linux
          - - self-hosted
            - macOS
            - ARM64
            - echoja-macos
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
      - uses: swatinem/rust-cache@v2
      - name: Run cargo test
        run: |
          cargo test
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    timeout-minutes: 20
    env:
      CARGO_HOME: ${{ runner.temp }}/cargo
      RUSTUP_HOME: ${{ runner.temp }}/rustup
